/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SalonsRouteImport } from './routes/salons'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as GlowAiRouteImport } from './routes/glow-ai'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SalonsIdRouteImport } from './routes/salons.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsRoute = SalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const GlowAiRoute = GlowAiRouteImport.update({
  id: '/glow-ai',
  path: '/glow-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const SalonsIdRoute = SalonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalonsRoute,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/glow-ai': typeof GlowAiRoute
  '/offers': typeof OffersRoute
  '/salons': typeof SalonsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/book/$id': typeof BookIdRoute
  '/salons/$id': typeof SalonsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/glow-ai': typeof GlowAiRoute
  '/offers': typeof OffersRoute
  '/salons': typeof SalonsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/book/$id': typeof BookIdRoute
  '/salons/$id': typeof SalonsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/glow-ai': typeof GlowAiRoute
  '/offers': typeof OffersRoute
  '/salons': typeof SalonsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/book/$id': typeof BookIdRoute
  '/salons/$id': typeof SalonsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-success'
    | '/dashboard'
    | '/glow-ai'
    | '/offers'
    | '/salons'
    | '/services'
    | '/signin'
    | '/book/$id'
    | '/salons/$id'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-success'
    | '/dashboard'
    | '/glow-ai'
    | '/offers'
    | '/salons'
    | '/services'
    | '/signin'
    | '/book/$id'
    | '/salons/$id'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/booking-success'
    | '/dashboard'
    | '/glow-ai'
    | '/offers'
    | '/salons'
    | '/services'
    | '/signin'
    | '/book/$id'
    | '/salons/$id'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  DashboardRoute: typeof DashboardRoute
  GlowAiRoute: typeof GlowAiRoute
  OffersRoute: typeof OffersRoute
  SalonsRoute: typeof SalonsRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SigninRoute: typeof SigninRoute
  BookIdRoute: typeof BookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons': {
      id: '/salons'
      path: '/salons'
      fullPath: '/salons'
      preLoaderRoute: typeof SalonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glow-ai': {
      id: '/glow-ai'
      path: '/glow-ai'
      fullPath: '/glow-ai'
      preLoaderRoute: typeof GlowAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/salons/$id': {
      id: '/salons/$id'
      path: '/$id'
      fullPath: '/salons/$id'
      preLoaderRoute: typeof SalonsIdRouteImport
      parentRoute: typeof SalonsRoute
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SalonsRouteChildren {
  SalonsIdRoute: typeof SalonsIdRoute
}

const SalonsRouteChildren: SalonsRouteChildren = {
  SalonsIdRoute: SalonsIdRoute,
}

const SalonsRouteWithChildren =
  SalonsRoute._addFileChildren(SalonsRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  DashboardRoute: DashboardRoute,
  GlowAiRoute: GlowAiRoute,
  OffersRoute: OffersRoute,
  SalonsRoute: SalonsRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SigninRoute: SigninRoute,
  BookIdRoute: BookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
